name: Deployment (Staging)

on:
  push:
    branches:
      - staging

jobs:
  deployment:
    name: Deployment to staging server
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Remote command execution
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            git pull
